# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1211, 778)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.process_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.process_tabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.process_tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.process_tabs.setDocumentMode(False)
        self.process_tabs.setMovable(False)
        self.process_tabs.setObjectName("process_tabs")
        self.tab_approx = QtWidgets.QWidget()
        self.tab_approx.setObjectName("tab_approx")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_approx)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filter_selector = QtWidgets.QComboBox(self.tab_approx)
        self.filter_selector.setMaximumSize(QtCore.QSize(311, 16777215))
        self.filter_selector.setObjectName("filter_selector")
        self.filter_selector.addItem("")
        self.filter_selector.addItem("")
        self.filter_selector.addItem("")
        self.filter_selector.addItem("")
        self.filter_selector.addItem("")
        self.gridLayout_2.addWidget(self.filter_selector, 0, 0, 1, 1)
        self.filter_data = QtWidgets.QStackedWidget(self.tab_approx)
        self.filter_data.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_data.sizePolicy().hasHeightForWidth())
        self.filter_data.setSizePolicy(sizePolicy)
        self.filter_data.setMaximumSize(QtCore.QSize(311, 16777215))
        self.filter_data.setFrameShape(QtWidgets.QFrame.Panel)
        self.filter_data.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filter_data.setObjectName("filter_data")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.filter_data.addWidget(self.page_1)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.filter_data.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.filter_data, 7, 0, 1, 1)
        self.approx_plot = QtWidgets.QTabWidget(self.tab_approx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.approx_plot.sizePolicy().hasHeightForWidth())
        self.approx_plot.setSizePolicy(sizePolicy)
        self.approx_plot.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.approx_plot.setDocumentMode(False)
        self.approx_plot.setObjectName("approx_plot")
        self.attenuation = QtWidgets.QWidget()
        self.attenuation.setObjectName("attenuation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.attenuation)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plot = QtWidgets.QStackedWidget(self.attenuation)
        self.plot.setObjectName("plot")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.plot.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.plot.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.plot, 0, 0, 1, 8)
        self.label = QtWidgets.QLabel(self.attenuation)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_x = QtWidgets.QTextEdit(self.attenuation)
        self.label_x.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x.setObjectName("label_x")
        self.gridLayout_3.addWidget(self.label_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.attenuation)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 1)
        self.min_x = QtWidgets.QDoubleSpinBox(self.attenuation)
        self.min_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x.setSuffix("")
        self.min_x.setDecimals(3)
        self.min_x.setObjectName("min_x")
        self.gridLayout_3.addWidget(self.min_x, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.attenuation)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_y = QtWidgets.QTextEdit(self.attenuation)
        self.label_y.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y.setObjectName("label_y")
        self.gridLayout_3.addWidget(self.label_y, 1, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.attenuation)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 6, 1, 1)
        self.min_y = QtWidgets.QDoubleSpinBox(self.attenuation)
        self.min_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y.setSuffix("")
        self.min_y.setDecimals(3)
        self.min_y.setObjectName("min_y")
        self.gridLayout_3.addWidget(self.min_y, 1, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.attenuation)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.scale_x = QtWidgets.QComboBox(self.attenuation)
        self.scale_x.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x.setObjectName("scale_x")
        self.scale_x.addItem("")
        self.scale_x.addItem("")
        self.gridLayout_3.addWidget(self.scale_x, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.attenuation)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 2, 1, 1)
        self.max_x = QtWidgets.QDoubleSpinBox(self.attenuation)
        self.max_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x.setSuffix("")
        self.max_x.setDecimals(3)
        self.max_x.setObjectName("max_x")
        self.gridLayout_3.addWidget(self.max_x, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.attenuation)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 4, 1, 1)
        self.scale_y = QtWidgets.QComboBox(self.attenuation)
        self.scale_y.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y.setObjectName("scale_y")
        self.scale_y.addItem("")
        self.scale_y.addItem("")
        self.gridLayout_3.addWidget(self.scale_y, 2, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.attenuation)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 6, 1, 1)
        self.max_y = QtWidgets.QDoubleSpinBox(self.attenuation)
        self.max_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y.setSuffix("")
        self.max_y.setDecimals(3)
        self.max_y.setObjectName("max_y")
        self.gridLayout_3.addWidget(self.max_y, 2, 7, 1, 1)
        self.auto_scale = QtWidgets.QPushButton(self.attenuation)
        self.auto_scale.setObjectName("auto_scale")
        self.gridLayout_3.addWidget(self.auto_scale, 3, 3, 1, 2)
        self.approx_plot.addTab(self.attenuation, "")
        self.norm_att = QtWidgets.QWidget()
        self.norm_att.setObjectName("norm_att")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.norm_att)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plot_2 = QtWidgets.QStackedWidget(self.norm_att)
        self.plot_2.setObjectName("plot_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.plot_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.plot_2.addWidget(self.page_5)
        self.gridLayout_4.addWidget(self.plot_2, 0, 0, 1, 8)
        self.label_12 = QtWidgets.QLabel(self.norm_att)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_x_2 = QtWidgets.QTextEdit(self.norm_att)
        self.label_x_2.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_2.setObjectName("label_x_2")
        self.gridLayout_4.addWidget(self.label_x_2, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.norm_att)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 2, 1, 1)
        self.min_x_2 = QtWidgets.QDoubleSpinBox(self.norm_att)
        self.min_x_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_2.setSuffix("")
        self.min_x_2.setDecimals(3)
        self.min_x_2.setObjectName("min_x_2")
        self.gridLayout_4.addWidget(self.min_x_2, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.norm_att)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_y_2 = QtWidgets.QTextEdit(self.norm_att)
        self.label_y_2.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_2.setObjectName("label_y_2")
        self.gridLayout_4.addWidget(self.label_y_2, 1, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.norm_att)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 6, 1, 1)
        self.min_y_2 = QtWidgets.QDoubleSpinBox(self.norm_att)
        self.min_y_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_2.setSuffix("")
        self.min_y_2.setDecimals(3)
        self.min_y_2.setObjectName("min_y_2")
        self.gridLayout_4.addWidget(self.min_y_2, 1, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.norm_att)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.scale_x_2 = QtWidgets.QComboBox(self.norm_att)
        self.scale_x_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_2.setObjectName("scale_x_2")
        self.scale_x_2.addItem("")
        self.scale_x_2.addItem("")
        self.gridLayout_4.addWidget(self.scale_x_2, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.norm_att)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 2, 1, 1)
        self.max_x_2 = QtWidgets.QDoubleSpinBox(self.norm_att)
        self.max_x_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_2.setSuffix("")
        self.max_x_2.setDecimals(3)
        self.max_x_2.setObjectName("max_x_2")
        self.gridLayout_4.addWidget(self.max_x_2, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.norm_att)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 4, 1, 1)
        self.scale_y_2 = QtWidgets.QComboBox(self.norm_att)
        self.scale_y_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_2.setObjectName("scale_y_2")
        self.scale_y_2.addItem("")
        self.scale_y_2.addItem("")
        self.gridLayout_4.addWidget(self.scale_y_2, 2, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.norm_att)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 6, 1, 1)
        self.max_y_2 = QtWidgets.QDoubleSpinBox(self.norm_att)
        self.max_y_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_2.setSuffix("")
        self.max_y_2.setDecimals(3)
        self.max_y_2.setObjectName("max_y_2")
        self.gridLayout_4.addWidget(self.max_y_2, 2, 7, 1, 1)
        self.auto_scale_2 = QtWidgets.QPushButton(self.norm_att)
        self.auto_scale_2.setObjectName("auto_scale_2")
        self.gridLayout_4.addWidget(self.auto_scale_2, 3, 3, 1, 2)
        self.approx_plot.addTab(self.norm_att, "")
        self.phase = QtWidgets.QWidget()
        self.phase.setObjectName("phase")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.phase)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plot_3 = QtWidgets.QStackedWidget(self.phase)
        self.plot_3.setObjectName("plot_3")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.plot_3.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.plot_3.addWidget(self.page_7)
        self.gridLayout_5.addWidget(self.plot_3, 0, 0, 1, 8)
        self.label_20 = QtWidgets.QLabel(self.phase)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_x_3 = QtWidgets.QTextEdit(self.phase)
        self.label_x_3.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_3.setObjectName("label_x_3")
        self.gridLayout_5.addWidget(self.label_x_3, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.phase)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 2, 1, 1)
        self.min_x_3 = QtWidgets.QDoubleSpinBox(self.phase)
        self.min_x_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_3.setSuffix("")
        self.min_x_3.setDecimals(3)
        self.min_x_3.setObjectName("min_x_3")
        self.gridLayout_5.addWidget(self.min_x_3, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.phase)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 4, 1, 1)
        self.label_y_3 = QtWidgets.QTextEdit(self.phase)
        self.label_y_3.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_3.setObjectName("label_y_3")
        self.gridLayout_5.addWidget(self.label_y_3, 1, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.phase)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 6, 1, 1)
        self.min_y_3 = QtWidgets.QDoubleSpinBox(self.phase)
        self.min_y_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_3.setSuffix("")
        self.min_y_3.setDecimals(3)
        self.min_y_3.setObjectName("min_y_3")
        self.gridLayout_5.addWidget(self.min_y_3, 1, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.phase)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 2, 0, 1, 1)
        self.scale_x_3 = QtWidgets.QComboBox(self.phase)
        self.scale_x_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_3.setObjectName("scale_x_3")
        self.scale_x_3.addItem("")
        self.scale_x_3.addItem("")
        self.gridLayout_5.addWidget(self.scale_x_3, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.phase)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 2, 1, 1)
        self.max_x_3 = QtWidgets.QDoubleSpinBox(self.phase)
        self.max_x_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_3.setSuffix("")
        self.max_x_3.setDecimals(3)
        self.max_x_3.setObjectName("max_x_3")
        self.gridLayout_5.addWidget(self.max_x_3, 2, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.phase)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 2, 4, 1, 1)
        self.scale_y_3 = QtWidgets.QComboBox(self.phase)
        self.scale_y_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_3.setObjectName("scale_y_3")
        self.scale_y_3.addItem("")
        self.scale_y_3.addItem("")
        self.gridLayout_5.addWidget(self.scale_y_3, 2, 5, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.phase)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 6, 1, 1)
        self.max_y_3 = QtWidgets.QDoubleSpinBox(self.phase)
        self.max_y_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_3.setSuffix("")
        self.max_y_3.setDecimals(3)
        self.max_y_3.setObjectName("max_y_3")
        self.gridLayout_5.addWidget(self.max_y_3, 2, 7, 1, 1)
        self.auto_scale_3 = QtWidgets.QPushButton(self.phase)
        self.auto_scale_3.setObjectName("auto_scale_3")
        self.gridLayout_5.addWidget(self.auto_scale_3, 3, 3, 1, 2)
        self.approx_plot.addTab(self.phase, "")
        self.group_delay = QtWidgets.QWidget()
        self.group_delay.setObjectName("group_delay")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_delay)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plot_4 = QtWidgets.QStackedWidget(self.group_delay)
        self.plot_4.setObjectName("plot_4")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.plot_4.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.plot_4.addWidget(self.page_9)
        self.gridLayout_6.addWidget(self.plot_4, 0, 0, 1, 8)
        self.label_28 = QtWidgets.QLabel(self.group_delay)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_x_4 = QtWidgets.QTextEdit(self.group_delay)
        self.label_x_4.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_4.setObjectName("label_x_4")
        self.gridLayout_6.addWidget(self.label_x_4, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.group_delay)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 2, 1, 1)
        self.min_x_4 = QtWidgets.QDoubleSpinBox(self.group_delay)
        self.min_x_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_4.setSuffix("")
        self.min_x_4.setDecimals(3)
        self.min_x_4.setObjectName("min_x_4")
        self.gridLayout_6.addWidget(self.min_x_4, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.group_delay)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 4, 1, 1)
        self.label_y_4 = QtWidgets.QTextEdit(self.group_delay)
        self.label_y_4.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_4.setObjectName("label_y_4")
        self.gridLayout_6.addWidget(self.label_y_4, 1, 5, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.group_delay)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 1, 6, 1, 1)
        self.min_y_4 = QtWidgets.QDoubleSpinBox(self.group_delay)
        self.min_y_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_4.setSuffix("")
        self.min_y_4.setDecimals(3)
        self.min_y_4.setObjectName("min_y_4")
        self.gridLayout_6.addWidget(self.min_y_4, 1, 7, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.group_delay)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 2, 0, 1, 1)
        self.scale_x_4 = QtWidgets.QComboBox(self.group_delay)
        self.scale_x_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_4.setObjectName("scale_x_4")
        self.scale_x_4.addItem("")
        self.scale_x_4.addItem("")
        self.gridLayout_6.addWidget(self.scale_x_4, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.group_delay)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 2, 2, 1, 1)
        self.max_x_4 = QtWidgets.QDoubleSpinBox(self.group_delay)
        self.max_x_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_4.setSuffix("")
        self.max_x_4.setDecimals(3)
        self.max_x_4.setObjectName("max_x_4")
        self.gridLayout_6.addWidget(self.max_x_4, 2, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.group_delay)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 4, 1, 1)
        self.scale_y_4 = QtWidgets.QComboBox(self.group_delay)
        self.scale_y_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_4.setObjectName("scale_y_4")
        self.scale_y_4.addItem("")
        self.scale_y_4.addItem("")
        self.gridLayout_6.addWidget(self.scale_y_4, 2, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.group_delay)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 6, 1, 1)
        self.max_y_4 = QtWidgets.QDoubleSpinBox(self.group_delay)
        self.max_y_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_4.setSuffix("")
        self.max_y_4.setDecimals(3)
        self.max_y_4.setObjectName("max_y_4")
        self.gridLayout_6.addWidget(self.max_y_4, 2, 7, 1, 1)
        self.auto_scale_4 = QtWidgets.QPushButton(self.group_delay)
        self.auto_scale_4.setObjectName("auto_scale_4")
        self.gridLayout_6.addWidget(self.auto_scale_4, 3, 3, 1, 2)
        self.approx_plot.addTab(self.group_delay, "")
        self.poles_zeros = QtWidgets.QWidget()
        self.poles_zeros.setObjectName("poles_zeros")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.poles_zeros)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plot_5 = QtWidgets.QStackedWidget(self.poles_zeros)
        self.plot_5.setObjectName("plot_5")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.plot_5.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.plot_5.addWidget(self.page_11)
        self.gridLayout_7.addWidget(self.plot_5, 0, 0, 1, 8)
        self.label_36 = QtWidgets.QLabel(self.poles_zeros)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 1, 0, 1, 1)
        self.label_x_5 = QtWidgets.QTextEdit(self.poles_zeros)
        self.label_x_5.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_5.setObjectName("label_x_5")
        self.gridLayout_7.addWidget(self.label_x_5, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.poles_zeros)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 1, 2, 1, 1)
        self.min_x_5 = QtWidgets.QDoubleSpinBox(self.poles_zeros)
        self.min_x_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_5.setSuffix("")
        self.min_x_5.setDecimals(3)
        self.min_x_5.setObjectName("min_x_5")
        self.gridLayout_7.addWidget(self.min_x_5, 1, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.poles_zeros)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 1, 4, 1, 1)
        self.label_y_5 = QtWidgets.QTextEdit(self.poles_zeros)
        self.label_y_5.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_5.setObjectName("label_y_5")
        self.gridLayout_7.addWidget(self.label_y_5, 1, 5, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.poles_zeros)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 1, 6, 1, 1)
        self.min_y_5 = QtWidgets.QDoubleSpinBox(self.poles_zeros)
        self.min_y_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_5.setSuffix("")
        self.min_y_5.setDecimals(3)
        self.min_y_5.setObjectName("min_y_5")
        self.gridLayout_7.addWidget(self.min_y_5, 1, 7, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.poles_zeros)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 2, 0, 1, 1)
        self.scale_x_5 = QtWidgets.QComboBox(self.poles_zeros)
        self.scale_x_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_5.setObjectName("scale_x_5")
        self.scale_x_5.addItem("")
        self.scale_x_5.addItem("")
        self.gridLayout_7.addWidget(self.scale_x_5, 2, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.poles_zeros)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 2, 2, 1, 1)
        self.max_x_5 = QtWidgets.QDoubleSpinBox(self.poles_zeros)
        self.max_x_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_5.setSuffix("")
        self.max_x_5.setDecimals(3)
        self.max_x_5.setObjectName("max_x_5")
        self.gridLayout_7.addWidget(self.max_x_5, 2, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.poles_zeros)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 4, 1, 1)
        self.scale_y_5 = QtWidgets.QComboBox(self.poles_zeros)
        self.scale_y_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_5.setObjectName("scale_y_5")
        self.scale_y_5.addItem("")
        self.scale_y_5.addItem("")
        self.gridLayout_7.addWidget(self.scale_y_5, 2, 5, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.poles_zeros)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 2, 6, 1, 1)
        self.max_y_5 = QtWidgets.QDoubleSpinBox(self.poles_zeros)
        self.max_y_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_5.setSuffix("")
        self.max_y_5.setDecimals(3)
        self.max_y_5.setObjectName("max_y_5")
        self.gridLayout_7.addWidget(self.max_y_5, 2, 7, 1, 1)
        self.auto_scale_5 = QtWidgets.QPushButton(self.poles_zeros)
        self.auto_scale_5.setObjectName("auto_scale_5")
        self.gridLayout_7.addWidget(self.auto_scale_5, 3, 3, 1, 2)
        self.approx_plot.addTab(self.poles_zeros, "")
        self.q_factor = QtWidgets.QWidget()
        self.q_factor.setObjectName("q_factor")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.q_factor)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plot_6 = QtWidgets.QStackedWidget(self.q_factor)
        self.plot_6.setObjectName("plot_6")
        self.page_24 = QtWidgets.QWidget()
        self.page_24.setObjectName("page_24")
        self.plot_6.addWidget(self.page_24)
        self.page_25 = QtWidgets.QWidget()
        self.page_25.setObjectName("page_25")
        self.plot_6.addWidget(self.page_25)
        self.gridLayout_8.addWidget(self.plot_6, 0, 0, 1, 8)
        self.label_44 = QtWidgets.QLabel(self.q_factor)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_x_6 = QtWidgets.QTextEdit(self.q_factor)
        self.label_x_6.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_6.setObjectName("label_x_6")
        self.gridLayout_8.addWidget(self.label_x_6, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.q_factor)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 1, 2, 1, 1)
        self.min_x_6 = QtWidgets.QDoubleSpinBox(self.q_factor)
        self.min_x_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_6.setSuffix("")
        self.min_x_6.setDecimals(3)
        self.min_x_6.setObjectName("min_x_6")
        self.gridLayout_8.addWidget(self.min_x_6, 1, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.q_factor)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 1, 4, 1, 1)
        self.label_y_6 = QtWidgets.QTextEdit(self.q_factor)
        self.label_y_6.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_6.setObjectName("label_y_6")
        self.gridLayout_8.addWidget(self.label_y_6, 1, 5, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.q_factor)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 1, 6, 1, 1)
        self.min_y_6 = QtWidgets.QDoubleSpinBox(self.q_factor)
        self.min_y_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_6.setSuffix("")
        self.min_y_6.setDecimals(3)
        self.min_y_6.setObjectName("min_y_6")
        self.gridLayout_8.addWidget(self.min_y_6, 1, 7, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.q_factor)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 2, 0, 1, 1)
        self.scale_x_6 = QtWidgets.QComboBox(self.q_factor)
        self.scale_x_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_6.setObjectName("scale_x_6")
        self.scale_x_6.addItem("")
        self.scale_x_6.addItem("")
        self.gridLayout_8.addWidget(self.scale_x_6, 2, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.q_factor)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 2, 1, 1)
        self.max_x_6 = QtWidgets.QDoubleSpinBox(self.q_factor)
        self.max_x_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_6.setSuffix("")
        self.max_x_6.setDecimals(3)
        self.max_x_6.setObjectName("max_x_6")
        self.gridLayout_8.addWidget(self.max_x_6, 2, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.q_factor)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 2, 4, 1, 1)
        self.scale_y_6 = QtWidgets.QComboBox(self.q_factor)
        self.scale_y_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_6.setObjectName("scale_y_6")
        self.scale_y_6.addItem("")
        self.scale_y_6.addItem("")
        self.gridLayout_8.addWidget(self.scale_y_6, 2, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.q_factor)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 2, 6, 1, 1)
        self.max_y_6 = QtWidgets.QDoubleSpinBox(self.q_factor)
        self.max_y_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_6.setSuffix("")
        self.max_y_6.setDecimals(3)
        self.max_y_6.setObjectName("max_y_6")
        self.gridLayout_8.addWidget(self.max_y_6, 2, 7, 1, 1)
        self.auto_scale_6 = QtWidgets.QPushButton(self.q_factor)
        self.auto_scale_6.setObjectName("auto_scale_6")
        self.gridLayout_8.addWidget(self.auto_scale_6, 3, 3, 1, 2)
        self.approx_plot.addTab(self.q_factor, "")
        self.impulse_res = QtWidgets.QWidget()
        self.impulse_res.setObjectName("impulse_res")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.impulse_res)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.plot_7 = QtWidgets.QStackedWidget(self.impulse_res)
        self.plot_7.setObjectName("plot_7")
        self.page_26 = QtWidgets.QWidget()
        self.page_26.setObjectName("page_26")
        self.plot_7.addWidget(self.page_26)
        self.page_27 = QtWidgets.QWidget()
        self.page_27.setObjectName("page_27")
        self.plot_7.addWidget(self.page_27)
        self.gridLayout_9.addWidget(self.plot_7, 0, 0, 1, 8)
        self.label_52 = QtWidgets.QLabel(self.impulse_res)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_9.addWidget(self.label_52, 1, 0, 1, 1)
        self.label_x_7 = QtWidgets.QTextEdit(self.impulse_res)
        self.label_x_7.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_7.setObjectName("label_x_7")
        self.gridLayout_9.addWidget(self.label_x_7, 1, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.impulse_res)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 1, 2, 1, 1)
        self.min_x_7 = QtWidgets.QDoubleSpinBox(self.impulse_res)
        self.min_x_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_7.setSuffix("")
        self.min_x_7.setDecimals(3)
        self.min_x_7.setObjectName("min_x_7")
        self.gridLayout_9.addWidget(self.min_x_7, 1, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.impulse_res)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 1, 4, 1, 1)
        self.label_y_7 = QtWidgets.QTextEdit(self.impulse_res)
        self.label_y_7.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_7.setObjectName("label_y_7")
        self.gridLayout_9.addWidget(self.label_y_7, 1, 5, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.impulse_res)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 1, 6, 1, 1)
        self.min_y_7 = QtWidgets.QDoubleSpinBox(self.impulse_res)
        self.min_y_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_7.setSuffix("")
        self.min_y_7.setDecimals(3)
        self.min_y_7.setObjectName("min_y_7")
        self.gridLayout_9.addWidget(self.min_y_7, 1, 7, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.impulse_res)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_9.addWidget(self.label_51, 2, 0, 1, 1)
        self.scale_x_7 = QtWidgets.QComboBox(self.impulse_res)
        self.scale_x_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_7.setObjectName("scale_x_7")
        self.scale_x_7.addItem("")
        self.scale_x_7.addItem("")
        self.gridLayout_9.addWidget(self.scale_x_7, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.impulse_res)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_9.addWidget(self.label_56, 2, 2, 1, 1)
        self.max_x_7 = QtWidgets.QDoubleSpinBox(self.impulse_res)
        self.max_x_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_7.setSuffix("")
        self.max_x_7.setDecimals(3)
        self.max_x_7.setObjectName("max_x_7")
        self.gridLayout_9.addWidget(self.max_x_7, 2, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.impulse_res)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_9.addWidget(self.label_54, 2, 4, 1, 1)
        self.scale_y_7 = QtWidgets.QComboBox(self.impulse_res)
        self.scale_y_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_7.setObjectName("scale_y_7")
        self.scale_y_7.addItem("")
        self.scale_y_7.addItem("")
        self.gridLayout_9.addWidget(self.scale_y_7, 2, 5, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.impulse_res)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 2, 6, 1, 1)
        self.max_y_7 = QtWidgets.QDoubleSpinBox(self.impulse_res)
        self.max_y_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_7.setSuffix("")
        self.max_y_7.setDecimals(3)
        self.max_y_7.setObjectName("max_y_7")
        self.gridLayout_9.addWidget(self.max_y_7, 2, 7, 1, 1)
        self.auto_scale_7 = QtWidgets.QPushButton(self.impulse_res)
        self.auto_scale_7.setObjectName("auto_scale_7")
        self.gridLayout_9.addWidget(self.auto_scale_7, 3, 3, 1, 2)
        self.approx_plot.addTab(self.impulse_res, "")
        self.step_res = QtWidgets.QWidget()
        self.step_res.setObjectName("step_res")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.step_res)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plot_8 = QtWidgets.QStackedWidget(self.step_res)
        self.plot_8.setObjectName("plot_8")
        self.page_28 = QtWidgets.QWidget()
        self.page_28.setObjectName("page_28")
        self.plot_8.addWidget(self.page_28)
        self.page_29 = QtWidgets.QWidget()
        self.page_29.setObjectName("page_29")
        self.plot_8.addWidget(self.page_29)
        self.gridLayout_10.addWidget(self.plot_8, 0, 0, 1, 8)
        self.label_60 = QtWidgets.QLabel(self.step_res)
        self.label_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_10.addWidget(self.label_60, 1, 0, 1, 1)
        self.label_x_8 = QtWidgets.QTextEdit(self.step_res)
        self.label_x_8.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_8.setObjectName("label_x_8")
        self.gridLayout_10.addWidget(self.label_x_8, 1, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.step_res)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 1, 2, 1, 1)
        self.min_x_8 = QtWidgets.QDoubleSpinBox(self.step_res)
        self.min_x_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_8.setSuffix("")
        self.min_x_8.setDecimals(3)
        self.min_x_8.setObjectName("min_x_8")
        self.gridLayout_10.addWidget(self.min_x_8, 1, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.step_res)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_10.addWidget(self.label_57, 1, 4, 1, 1)
        self.label_y_8 = QtWidgets.QTextEdit(self.step_res)
        self.label_y_8.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_8.setObjectName("label_y_8")
        self.gridLayout_10.addWidget(self.label_y_8, 1, 5, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.step_res)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 1, 6, 1, 1)
        self.min_y_8 = QtWidgets.QDoubleSpinBox(self.step_res)
        self.min_y_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_8.setSuffix("")
        self.min_y_8.setDecimals(3)
        self.min_y_8.setObjectName("min_y_8")
        self.gridLayout_10.addWidget(self.min_y_8, 1, 7, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.step_res)
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 2, 0, 1, 1)
        self.scale_x_8 = QtWidgets.QComboBox(self.step_res)
        self.scale_x_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_8.setObjectName("scale_x_8")
        self.scale_x_8.addItem("")
        self.scale_x_8.addItem("")
        self.gridLayout_10.addWidget(self.scale_x_8, 2, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.step_res)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_10.addWidget(self.label_64, 2, 2, 1, 1)
        self.max_x_8 = QtWidgets.QDoubleSpinBox(self.step_res)
        self.max_x_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_8.setSuffix("")
        self.max_x_8.setDecimals(3)
        self.max_x_8.setObjectName("max_x_8")
        self.gridLayout_10.addWidget(self.max_x_8, 2, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.step_res)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_10.addWidget(self.label_62, 2, 4, 1, 1)
        self.scale_y_8 = QtWidgets.QComboBox(self.step_res)
        self.scale_y_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_8.setObjectName("scale_y_8")
        self.scale_y_8.addItem("")
        self.scale_y_8.addItem("")
        self.gridLayout_10.addWidget(self.scale_y_8, 2, 5, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.step_res)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_10.addWidget(self.label_61, 2, 6, 1, 1)
        self.max_y_8 = QtWidgets.QDoubleSpinBox(self.step_res)
        self.max_y_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_8.setSuffix("")
        self.max_y_8.setDecimals(3)
        self.max_y_8.setObjectName("max_y_8")
        self.gridLayout_10.addWidget(self.max_y_8, 2, 7, 1, 1)
        self.auto_scale_8 = QtWidgets.QPushButton(self.step_res)
        self.auto_scale_8.setObjectName("auto_scale_8")
        self.gridLayout_10.addWidget(self.auto_scale_8, 3, 3, 1, 2)
        self.approx_plot.addTab(self.step_res, "")
        self.gridLayout_2.addWidget(self.approx_plot, 0, 1, 8, 1)
        self.template_pic = QtWidgets.QStackedWidget(self.tab_approx)
        self.template_pic.setMaximumSize(QtCore.QSize(311, 230))
        self.template_pic.setObjectName("template_pic")
        self.lp_pic = QtWidgets.QWidget()
        self.lp_pic.setObjectName("lp_pic")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.lp_pic)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_66 = QtWidgets.QLabel(self.lp_pic)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_12.addWidget(self.label_66, 0, 0, 1, 1)
        self.template_pic.addWidget(self.lp_pic)
        self.hp_pic = QtWidgets.QWidget()
        self.hp_pic.setObjectName("hp_pic")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.hp_pic)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_67 = QtWidgets.QLabel(self.hp_pic)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_13.addWidget(self.label_67, 0, 0, 1, 1)
        self.template_pic.addWidget(self.hp_pic)
        self.bp_pic = QtWidgets.QWidget()
        self.bp_pic.setObjectName("bp_pic")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.bp_pic)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_65 = QtWidgets.QLabel(self.bp_pic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_11.addWidget(self.label_65, 0, 0, 1, 1)
        self.template_pic.addWidget(self.bp_pic)
        self.bs_pic = QtWidgets.QWidget()
        self.bs_pic.setObjectName("bs_pic")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.bs_pic)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_68 = QtWidgets.QLabel(self.bs_pic)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_14.addWidget(self.label_68, 0, 0, 1, 1)
        self.template_pic.addWidget(self.bs_pic)
        self.gd_pic = QtWidgets.QWidget()
        self.gd_pic.setObjectName("gd_pic")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gd_pic)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_69 = QtWidgets.QLabel(self.gd_pic)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_15.addWidget(self.label_69, 1, 0, 1, 1)
        self.template_pic.addWidget(self.gd_pic)
        self.gridLayout_2.addWidget(self.template_pic, 2, 0, 1, 1)
        self.approx_selector = QtWidgets.QComboBox(self.tab_approx)
        self.approx_selector.setMaximumSize(QtCore.QSize(311, 16777215))
        self.approx_selector.setObjectName("approx_selector")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.approx_selector.addItem("")
        self.gridLayout_2.addWidget(self.approx_selector, 1, 0, 1, 1)
        self.process_tabs.addTab(self.tab_approx, "")
        self.tab_stages = QtWidgets.QWidget()
        self.tab_stages.setObjectName("tab_stages")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_stages)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_78 = QtWidgets.QLabel(self.tab_stages)
        self.label_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_16.addWidget(self.label_78, 0, 0, 1, 1)
        self.label_y_stages = QtWidgets.QTextEdit(self.tab_stages)
        self.label_y_stages.setMaximumSize(QtCore.QSize(100, 26))
        self.label_y_stages.setObjectName("label_y_stages")
        self.gridLayout_16.addWidget(self.label_y_stages, 2, 1, 1, 3)
        self.label_x_stages = QtWidgets.QTextEdit(self.tab_stages)
        self.label_x_stages.setMaximumSize(QtCore.QSize(100, 26))
        self.label_x_stages.setObjectName("label_x_stages")
        self.gridLayout_16.addWidget(self.label_x_stages, 0, 1, 1, 3)
        self.label_76 = QtWidgets.QLabel(self.tab_stages)
        self.label_76.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_16.addWidget(self.label_76, 0, 5, 1, 2)
        self.label_77 = QtWidgets.QLabel(self.tab_stages)
        self.label_77.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_77.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_16.addWidget(self.label_77, 2, 5, 1, 2)
        self.label_79 = QtWidgets.QLabel(self.tab_stages)
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_16.addWidget(self.label_79, 2, 0, 1, 1)
        self.max_x_stages = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.max_x_stages.setMaximumSize(QtCore.QSize(93, 16777215))
        self.max_x_stages.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_stages.setSuffix("")
        self.max_x_stages.setDecimals(3)
        self.max_x_stages.setObjectName("max_x_stages")
        self.gridLayout_16.addWidget(self.max_x_stages, 1, 8, 1, 2)
        self.label_75 = QtWidgets.QLabel(self.tab_stages)
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_16.addWidget(self.label_75, 1, 0, 1, 1)
        self.min_x_stages = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.min_x_stages.setMaximumSize(QtCore.QSize(93, 16777215))
        self.min_x_stages.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_stages.setSuffix("")
        self.min_x_stages.setDecimals(3)
        self.min_x_stages.setObjectName("min_x_stages")
        self.gridLayout_16.addWidget(self.min_x_stages, 0, 8, 1, 2)
        self.stage_plot = QtWidgets.QStackedWidget(self.tab_stages)
        self.stage_plot.setObjectName("stage_plot")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.stage_plot.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.stage_plot.addWidget(self.page_13)
        self.gridLayout_16.addWidget(self.stage_plot, 0, 10, 8, 1)
        self.scale_x_stages = QtWidgets.QComboBox(self.tab_stages)
        self.scale_x_stages.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_x_stages.setObjectName("scale_x_stages")
        self.scale_x_stages.addItem("")
        self.scale_x_stages.addItem("")
        self.gridLayout_16.addWidget(self.scale_x_stages, 1, 1, 1, 3)
        self.label_72 = QtWidgets.QLabel(self.tab_stages)
        self.label_72.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_16.addWidget(self.label_72, 1, 5, 1, 2)
        self.min_y_stages = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.min_y_stages.setMaximumSize(QtCore.QSize(93, 16777215))
        self.min_y_stages.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_y_stages.setSuffix("")
        self.min_y_stages.setDecimals(3)
        self.min_y_stages.setObjectName("min_y_stages")
        self.gridLayout_16.addWidget(self.min_y_stages, 2, 8, 1, 2)
        self.auto_scale_stages = QtWidgets.QPushButton(self.tab_stages)
        self.auto_scale_stages.setObjectName("auto_scale_stages")
        self.gridLayout_16.addWidget(self.auto_scale_stages, 4, 0, 1, 3)
        self.scale_y_stages = QtWidgets.QComboBox(self.tab_stages)
        self.scale_y_stages.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scale_y_stages.setObjectName("scale_y_stages")
        self.scale_y_stages.addItem("")
        self.scale_y_stages.addItem("")
        self.gridLayout_16.addWidget(self.scale_y_stages, 3, 1, 1, 3)
        self.max_y_stages = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.max_y_stages.setMaximumSize(QtCore.QSize(93, 16777215))
        self.max_y_stages.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_y_stages.setSuffix("")
        self.max_y_stages.setDecimals(3)
        self.max_y_stages.setObjectName("max_y_stages")
        self.gridLayout_16.addWidget(self.max_y_stages, 3, 8, 1, 2)
        self.label_73 = QtWidgets.QLabel(self.tab_stages)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_16.addWidget(self.label_73, 3, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab_stages)
        self.label_70.setObjectName("label_70")
        self.gridLayout_16.addWidget(self.label_70, 5, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab_stages)
        self.label_71.setObjectName("label_71")
        self.gridLayout_16.addWidget(self.label_71, 5, 5, 1, 2)
        self.poles_list = QtWidgets.QListView(self.tab_stages)
        self.poles_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poles_list.setObjectName("poles_list")
        self.gridLayout_16.addWidget(self.poles_list, 6, 0, 1, 4)
        self.label_74 = QtWidgets.QLabel(self.tab_stages)
        self.label_74.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_16.addWidget(self.label_74, 3, 5, 1, 2)
        self.zeros_list = QtWidgets.QListView(self.tab_stages)
        self.zeros_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.zeros_list.setObjectName("zeros_list")
        self.gridLayout_16.addWidget(self.zeros_list, 6, 5, 1, 5)
        self.automatic_cascade = QtWidgets.QPushButton(self.tab_stages)
        self.automatic_cascade.setObjectName("automatic_cascade")
        self.gridLayout_16.addWidget(self.automatic_cascade, 7, 0, 1, 2)
        self.min_x_stages_3 = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.min_x_stages_3.setMaximumSize(QtCore.QSize(93, 16777215))
        self.min_x_stages_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_x_stages_3.setSuffix("")
        self.min_x_stages_3.setDecimals(2)
        self.min_x_stages_3.setObjectName("min_x_stages_3")
        self.gridLayout_16.addWidget(self.min_x_stages_3, 7, 3, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.tab_stages)
        self.label_80.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_16.addWidget(self.label_80, 7, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.tab_stages)
        self.label_82.setMaximumSize(QtCore.QSize(93, 16777215))
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_16.addWidget(self.label_82, 7, 4, 1, 2)
        self.max_x_stages_3 = QtWidgets.QDoubleSpinBox(self.tab_stages)
        self.max_x_stages_3.setMaximumSize(QtCore.QSize(93, 16777215))
        self.max_x_stages_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_x_stages_3.setSuffix("")
        self.max_x_stages_3.setDecimals(2)
        self.max_x_stages_3.setObjectName("max_x_stages_3")
        self.gridLayout_16.addWidget(self.max_x_stages_3, 7, 6, 1, 1)
        self.stages_list = QtWidgets.QColumnView(self.tab_stages)
        self.stages_list.setDragEnabled(True)
        self.stages_list.setDragDropOverwriteMode(True)
        self.stages_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.stages_list.setObjectName("stages_list")
        self.gridLayout_16.addWidget(self.stages_list, 8, 0, 1, 11)
        self.label_81 = QtWidgets.QLabel(self.tab_stages)
        self.label_81.setObjectName("label_81")
        self.gridLayout_16.addWidget(self.label_81, 7, 7, 1, 2)
        self.order_2 = QtWidgets.QLabel(self.tab_stages)
        self.order_2.setObjectName("order_2")
        self.gridLayout_16.addWidget(self.order_2, 7, 9, 1, 1)
        self.accumulative_plot = QtWidgets.QCheckBox(self.tab_stages)
        self.accumulative_plot.setObjectName("accumulative_plot")
        self.gridLayout_16.addWidget(self.accumulative_plot, 4, 5, 1, 3)
        self.process_tabs.addTab(self.tab_stages, "")
        self.tab_cells = QtWidgets.QWidget()
        self.tab_cells.setObjectName("tab_cells")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_cells)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.stages_list_cells = QtWidgets.QColumnView(self.tab_cells)
        self.stages_list_cells.setMaximumSize(QtCore.QSize(16777215, 233))
        self.stages_list_cells.setDragEnabled(True)
        self.stages_list_cells.setDragDropOverwriteMode(True)
        self.stages_list_cells.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.stages_list_cells.setObjectName("stages_list_cells")
        self.gridLayout_17.addWidget(self.stages_list_cells, 2, 0, 1, 2)
        self.circuits_list = QtWidgets.QColumnView(self.tab_cells)
        self.circuits_list.setDragEnabled(True)
        self.circuits_list.setDragDropOverwriteMode(True)
        self.circuits_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.circuits_list.setObjectName("circuits_list")
        self.gridLayout_17.addWidget(self.circuits_list, 0, 0, 2, 1)
        self.cells_settings = QtWidgets.QStackedWidget(self.tab_cells)
        self.cells_settings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cells_settings.setObjectName("cells_settings")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.cells_settings.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.cells_settings.addWidget(self.page_15)
        self.gridLayout_17.addWidget(self.cells_settings, 0, 1, 1, 1)
        self.process_tabs.addTab(self.tab_cells, "")
        self.gridLayout.addWidget(self.process_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.process_tabs.setCurrentIndex(1)
        self.filter_data.setCurrentIndex(1)
        self.approx_plot.setCurrentIndex(0)
        self.template_pic.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filters Tool"))
        self.filter_selector.setItemText(0, _translate("MainWindow", "Low-Pass"))
        self.filter_selector.setItemText(1, _translate("MainWindow", "High-Pass"))
        self.filter_selector.setItemText(2, _translate("MainWindow", "Band-Pass"))
        self.filter_selector.setItemText(3, _translate("MainWindow", "Band-Stop"))
        self.filter_selector.setItemText(4, _translate("MainWindow", "Group-Delay"))
        self.label.setText(_translate("MainWindow", "Label X"))
        self.label_3.setText(_translate("MainWindow", "Minimum X"))
        self.label_5.setText(_translate("MainWindow", "Label Y"))
        self.label_7.setText(_translate("MainWindow", "Minimum Y"))
        self.label_2.setText(_translate("MainWindow", "Scale X"))
        self.scale_x.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_4.setText(_translate("MainWindow", "Maximum X"))
        self.label_6.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_8.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.attenuation), _translate("MainWindow", "Attenuation"))
        self.label_12.setText(_translate("MainWindow", "Label X"))
        self.label_10.setText(_translate("MainWindow", "Minimum X"))
        self.label_9.setText(_translate("MainWindow", "Label Y"))
        self.label_15.setText(_translate("MainWindow", "Minimum Y"))
        self.label_11.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_2.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_2.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_16.setText(_translate("MainWindow", "Maximum X"))
        self.label_14.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_2.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_2.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_13.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_2.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.norm_att), _translate("MainWindow", "Normalised Att."))
        self.label_20.setText(_translate("MainWindow", "Label X"))
        self.label_18.setText(_translate("MainWindow", "Minimum X"))
        self.label_17.setText(_translate("MainWindow", "Label Y"))
        self.label_23.setText(_translate("MainWindow", "Minimum Y"))
        self.label_19.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_3.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_3.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_24.setText(_translate("MainWindow", "Maximum X"))
        self.label_22.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_3.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_3.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_21.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_3.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.phase), _translate("MainWindow", "Phase"))
        self.label_28.setText(_translate("MainWindow", "Label X"))
        self.label_26.setText(_translate("MainWindow", "Minimum X"))
        self.label_25.setText(_translate("MainWindow", "Label Y"))
        self.label_31.setText(_translate("MainWindow", "Minimum Y"))
        self.label_27.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_4.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_4.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_32.setText(_translate("MainWindow", "Maximum X"))
        self.label_30.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_4.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_4.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_29.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_4.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.group_delay), _translate("MainWindow", "Group Delay"))
        self.label_36.setText(_translate("MainWindow", "Label X"))
        self.label_34.setText(_translate("MainWindow", "Minimum X"))
        self.label_33.setText(_translate("MainWindow", "Label Y"))
        self.label_39.setText(_translate("MainWindow", "Minimum Y"))
        self.label_35.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_5.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_5.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_40.setText(_translate("MainWindow", "Maximum X"))
        self.label_38.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_5.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_5.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_37.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_5.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.poles_zeros), _translate("MainWindow", "Poles and Zeros"))
        self.label_44.setText(_translate("MainWindow", "Label X"))
        self.label_42.setText(_translate("MainWindow", "Minimum X"))
        self.label_41.setText(_translate("MainWindow", "Label Y"))
        self.label_47.setText(_translate("MainWindow", "Minimum Y"))
        self.label_43.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_6.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_6.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_48.setText(_translate("MainWindow", "Maximum X"))
        self.label_46.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_6.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_6.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_45.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_6.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.q_factor), _translate("MainWindow", "Q factor"))
        self.label_52.setText(_translate("MainWindow", "Label X"))
        self.label_50.setText(_translate("MainWindow", "Minimum X"))
        self.label_49.setText(_translate("MainWindow", "Label Y"))
        self.label_55.setText(_translate("MainWindow", "Minimum Y"))
        self.label_51.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_7.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_7.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_56.setText(_translate("MainWindow", "Maximum X"))
        self.label_54.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_7.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_7.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_53.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_7.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.impulse_res), _translate("MainWindow", "Impulse Response"))
        self.label_60.setText(_translate("MainWindow", "Label X"))
        self.label_58.setText(_translate("MainWindow", "Minimum X"))
        self.label_57.setText(_translate("MainWindow", "Label Y"))
        self.label_63.setText(_translate("MainWindow", "Minimum Y"))
        self.label_59.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_8.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_8.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_64.setText(_translate("MainWindow", "Maximum X"))
        self.label_62.setText(_translate("MainWindow", "Scale Y"))
        self.scale_y_8.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_8.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_61.setText(_translate("MainWindow", "Maximum Y"))
        self.auto_scale_8.setText(_translate("MainWindow", "Auto Scale"))
        self.approx_plot.setTabText(self.approx_plot.indexOf(self.step_res), _translate("MainWindow", "Step Response"))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/lp_template/LP_template.jpg\"/></p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/hp_template/HP_template.jpg\"/></p></body></html>"))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/bp_template/BP_template.jpg\"/></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/bs_template/bs_template.png\"/></p></body></html>"))
        self.label_69.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/lp_template/LP_template.jpg\"/></p></body></html>"))
        self.approx_selector.setItemText(0, _translate("MainWindow", "Butterworth"))
        self.approx_selector.setItemText(1, _translate("MainWindow", "Chebyshev I"))
        self.approx_selector.setItemText(2, _translate("MainWindow", "Chebyshev II"))
        self.approx_selector.setItemText(3, _translate("MainWindow", "Legendre"))
        self.approx_selector.setItemText(4, _translate("MainWindow", "Bessel"))
        self.approx_selector.setItemText(5, _translate("MainWindow", "Gauss"))
        self.approx_selector.setItemText(6, _translate("MainWindow", "Cauer"))
        self.process_tabs.setTabText(self.process_tabs.indexOf(self.tab_approx), _translate("MainWindow", "Filter and Approximation"))
        self.label_78.setText(_translate("MainWindow", "Label X"))
        self.label_76.setText(_translate("MainWindow", "Minimum X"))
        self.label_77.setText(_translate("MainWindow", "Minimum Y"))
        self.label_79.setText(_translate("MainWindow", "Label Y"))
        self.label_75.setText(_translate("MainWindow", "Scale X"))
        self.scale_x_stages.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_x_stages.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_72.setText(_translate("MainWindow", "Maximum X"))
        self.auto_scale_stages.setText(_translate("MainWindow", "Auto Scale"))
        self.scale_y_stages.setItemText(0, _translate("MainWindow", "Linear"))
        self.scale_y_stages.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_73.setText(_translate("MainWindow", "Scale Y"))
        self.label_70.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Poles:</span></p></body></html>"))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Zeros:</span></p></body></html>"))
        self.label_74.setText(_translate("MainWindow", "Maximum Y"))
        self.automatic_cascade.setText(_translate("MainWindow", "Automatic Cascade"))
        self.label_80.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">min</span></p></body></html>"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">max</span></p></body></html>"))
        self.label_81.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">DR</span><span style=\" font-size:10pt; vertical-align:sub;\">TOTAL</span><span style=\" font-size:10pt;\">:</span></p></body></html>"))
        self.order_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">40dB</span></p></body></html>"))
        self.accumulative_plot.setText(_translate("MainWindow", "Acumulative"))
        self.process_tabs.setTabText(self.process_tabs.indexOf(self.tab_stages), _translate("MainWindow", "Stages"))
        self.process_tabs.setTabText(self.process_tabs.indexOf(self.tab_cells), _translate("MainWindow", "Cells"))
import BP_template_rc
import BS_template_rc
import HP_template_rc
import LP_template_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
