# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_delay.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_group_delay_data(object):
    def setupUi(self, group_delay_data):
        group_delay_data.setObjectName("group_delay_data")
        group_delay_data.resize(311, 408)
        group_delay_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(group_delay_data)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(group_delay_data)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.pass_freq = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.pass_freq.setFrame(True)
        self.pass_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pass_freq.setKeyboardTracking(True)
        self.pass_freq.setDecimals(3)
        self.pass_freq.setObjectName("pass_freq")
        self.gridLayout.addWidget(self.pass_freq, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(group_delay_data)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(group_delay_data)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gain = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.gain.setFrame(True)
        self.gain.setAlignment(QtCore.Qt.AlignCenter)
        self.gain.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gain.setKeyboardTracking(True)
        self.gain.setDecimals(3)
        self.gain.setObjectName("gain")
        self.gridLayout.addWidget(self.gain, 0, 2, 1, 1)
        self.q_max = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.q_max.setFrame(True)
        self.q_max.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.q_max.setKeyboardTracking(True)
        self.q_max.setDecimals(3)
        self.q_max.setObjectName("q_max")
        self.gridLayout.addWidget(self.q_max, 5, 2, 1, 1)
        self.order_fixed = QtWidgets.QCheckBox(group_delay_data)
        self.order_fixed.setObjectName("order_fixed")
        self.gridLayout.addWidget(self.order_fixed, 4, 1, 1, 1)
        self.group_delay = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.group_delay.setFrame(True)
        self.group_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.group_delay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.group_delay.setKeyboardTracking(True)
        self.group_delay.setDecimals(3)
        self.group_delay.setObjectName("group_delay")
        self.gridLayout.addWidget(self.group_delay, 2, 2, 1, 1)
        self.tol = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.tol.setFrame(True)
        self.tol.setAlignment(QtCore.Qt.AlignCenter)
        self.tol.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tol.setKeyboardTracking(True)
        self.tol.setDecimals(3)
        self.tol.setProperty("value", 10.0)
        self.tol.setObjectName("tol")
        self.gridLayout.addWidget(self.tol, 3, 2, 1, 1)
        self.order = QtWidgets.QDoubleSpinBox(group_delay_data)
        self.order.setFrame(True)
        self.order.setAlignment(QtCore.Qt.AlignCenter)
        self.order.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.order.setKeyboardTracking(True)
        self.order.setDecimals(3)
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(group_delay_data)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(group_delay_data)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(group_delay_data)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.q_fixed = QtWidgets.QCheckBox(group_delay_data)
        self.q_fixed.setObjectName("q_fixed")
        self.gridLayout.addWidget(self.q_fixed, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(group_delay_data)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(group_delay_data)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(group_delay_data)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(group_delay_data)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)

        self.retranslateUi(group_delay_data)
        QtCore.QMetaObject.connectSlotsByName(group_delay_data)

    def retranslateUi(self, group_delay_data):
        _translate = QtCore.QCoreApplication.translate
        group_delay_data.setWindowTitle(_translate("group_delay_data", "Form"))
        self.label_3.setText(_translate("group_delay_data", "Passband freq. (fp):"))
        self.label_4.setText(_translate("group_delay_data", "Hz"))
        self.label.setText(_translate("group_delay_data", "Gain (G):"))
        self.order_fixed.setText(_translate("group_delay_data", "Fixed:"))
        self.label_11.setText(_translate("group_delay_data", "Tolerance:"))
        self.label_5.setText(_translate("group_delay_data", "Group-Delay (τg):"))
        self.label_15.setText(_translate("group_delay_data", "Max Q"))
        self.q_fixed.setText(_translate("group_delay_data", "Fixed:"))
        self.label_6.setText(_translate("group_delay_data", "ms"))
        self.label_13.setText(_translate("group_delay_data", "Filter order:"))
        self.label_12.setText(_translate("group_delay_data", "%"))
        self.label_2.setText(_translate("group_delay_data", "dB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    group_delay_data = QtWidgets.QWidget()
    ui = Ui_group_delay_data()
    ui.setupUi(group_delay_data)
    group_delay_data.show()
    sys.exit(app.exec_())
