# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_delay.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupDelayData(object):
    def setupUi(self, GroupDelayData):
        GroupDelayData.setObjectName("GroupDelayData")
        GroupDelayData.resize(376, 408)
        GroupDelayData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(GroupDelayData)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(GroupDelayData)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(GroupDelayData)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(GroupDelayData)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.stop_att = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.stop_att.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_att.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_att.setDecimals(3)
        self.stop_att.setMaximum(300.0)
        self.stop_att.setObjectName("stop_att")
        self.gridLayout.addWidget(self.stop_att, 5, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(GroupDelayData)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(GroupDelayData)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(GroupDelayData)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(GroupDelayData)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(GroupDelayData)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 4, 1, 1)
        self.q_max = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.q_max.setFrame(True)
        self.q_max.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.q_max.setKeyboardTracking(True)
        self.q_max.setDecimals(3)
        self.q_max.setMaximum(100.0)
        self.q_max.setObjectName("q_max")
        self.gridLayout.addWidget(self.q_max, 10, 2, 1, 1)
        self.tol = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.tol.setFrame(True)
        self.tol.setAlignment(QtCore.Qt.AlignCenter)
        self.tol.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tol.setKeyboardTracking(True)
        self.tol.setDecimals(3)
        self.tol.setMaximum(100.0)
        self.tol.setProperty("value", 10.0)
        self.tol.setObjectName("tol")
        self.gridLayout.addWidget(self.tol, 8, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(GroupDelayData)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(GroupDelayData)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(GroupDelayData)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(GroupDelayData)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(GroupDelayData)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.group_delay = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.group_delay.setFrame(True)
        self.group_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.group_delay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.group_delay.setKeyboardTracking(True)
        self.group_delay.setDecimals(3)
        self.group_delay.setMaximum(1000000000000.0)
        self.group_delay.setObjectName("group_delay")
        self.gridLayout.addWidget(self.group_delay, 7, 2, 1, 1)
        self.q_fixed = QtWidgets.QCheckBox(GroupDelayData)
        self.q_fixed.setAutoExclusive(False)
        self.q_fixed.setObjectName("q_fixed")
        self.gridLayout.addWidget(self.q_fixed, 10, 1, 1, 1)
        self.stop_freq = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.stop_freq.setFrame(True)
        self.stop_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_freq.setKeyboardTracking(True)
        self.stop_freq.setDecimals(3)
        self.stop_freq.setMaximum(1000000000000.0)
        self.stop_freq.setObjectName("stop_freq")
        self.gridLayout.addWidget(self.stop_freq, 3, 2, 1, 1)
        self.gain = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.gain.setFrame(True)
        self.gain.setAlignment(QtCore.Qt.AlignCenter)
        self.gain.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gain.setKeyboardTracking(True)
        self.gain.setDecimals(3)
        self.gain.setMaximum(300.0)
        self.gain.setObjectName("gain")
        self.gridLayout.addWidget(self.gain, 0, 2, 1, 1)
        self.order_fixed = QtWidgets.QCheckBox(GroupDelayData)
        self.order_fixed.setAutoExclusive(False)
        self.order_fixed.setObjectName("order_fixed")
        self.gridLayout.addWidget(self.order_fixed, 9, 1, 1, 1)
        self.order = QtWidgets.QSpinBox(GroupDelayData)
        self.order.setFrame(True)
        self.order.setAlignment(QtCore.Qt.AlignCenter)
        self.order.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.order.setKeyboardTracking(True)
        self.order.setMaximum(20)
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 9, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(GroupDelayData)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 2)
        self.group_delay_freq = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.group_delay_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.group_delay_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.group_delay_freq.setDecimals(3)
        self.group_delay_freq.setMaximum(1000000000000.0)
        self.group_delay_freq.setObjectName("group_delay_freq")
        self.gridLayout.addWidget(self.group_delay_freq, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(GroupDelayData)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(GroupDelayData)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.pass_freq = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.pass_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pass_freq.setDecimals(3)
        self.pass_freq.setMaximum(1000000000000.0)
        self.pass_freq.setObjectName("pass_freq")
        self.gridLayout.addWidget(self.pass_freq, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(GroupDelayData)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 4, 1, 1)
        self.pass_att = QtWidgets.QDoubleSpinBox(GroupDelayData)
        self.pass_att.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_att.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pass_att.setDecimals(3)
        self.pass_att.setMaximum(300.0)
        self.pass_att.setObjectName("pass_att")
        self.gridLayout.addWidget(self.pass_att, 4, 2, 1, 1)

        self.retranslateUi(GroupDelayData)
        QtCore.QMetaObject.connectSlotsByName(GroupDelayData)

    def retranslateUi(self, GroupDelayData):
        _translate = QtCore.QCoreApplication.translate
        GroupDelayData.setWindowTitle(_translate("GroupDelayData", "Form"))
        self.label_14.setText(_translate("GroupDelayData", "Passband freq. (fp):"))
        self.label_8.setText(_translate("GroupDelayData", "dB"))
        self.label_7.setText(_translate("GroupDelayData", "Stopband Att. (Aa):"))
        self.label_15.setText(_translate("GroupDelayData", "Max Q"))
        self.label.setText(_translate("GroupDelayData", "Gain (G):"))
        self.label_12.setText(_translate("GroupDelayData", "%"))
        self.label_13.setText(_translate("GroupDelayData", "Filter order:"))
        self.label_6.setText(_translate("GroupDelayData", "ms"))
        self.label_5.setText(_translate("GroupDelayData", "Group-Delay (τg):"))
        self.label_11.setText(_translate("GroupDelayData", "Tolerance:"))
        self.label_4.setText(_translate("GroupDelayData", "Hz"))
        self.label_3.setText(_translate("GroupDelayData", "Stopband freq. (fa):"))
        self.label_2.setText(_translate("GroupDelayData", "dB"))
        self.q_fixed.setText(_translate("GroupDelayData", "Fixed:"))
        self.order_fixed.setText(_translate("GroupDelayData", "Fixed:"))
        self.label_9.setText(_translate("GroupDelayData", "Group-Delay freq. (fτ):"))
        self.label_10.setText(_translate("GroupDelayData", "Hz"))
        self.label_16.setText(_translate("GroupDelayData", "Passband Att. (Ap):"))
        self.label_17.setText(_translate("GroupDelayData", "Hz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupDelayData = QtWidgets.QWidget()
    ui = Ui_GroupDelayData()
    ui.setupUi(GroupDelayData)
    GroupDelayData.show()
    sys.exit(app.exec_())
