# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'low_pass.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LowPassData(object):
    def setupUi(self, LowPassData):
        LowPassData.setObjectName("LowPassData")
        LowPassData.resize(311, 408)
        LowPassData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(LowPassData)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(LowPassData)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LowPassData)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(LowPassData)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.pass_att = QtWidgets.QDoubleSpinBox(LowPassData)
        self.pass_att.setFrame(True)
        self.pass_att.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_att.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pass_att.setKeyboardTracking(True)
        self.pass_att.setDecimals(3)
        self.pass_att.setObjectName("pass_att")
        self.gridLayout.addWidget(self.pass_att, 3, 2, 1, 1)
        self.stop_att = QtWidgets.QDoubleSpinBox(LowPassData)
        self.stop_att.setFrame(True)
        self.stop_att.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_att.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_att.setKeyboardTracking(True)
        self.stop_att.setDecimals(3)
        self.stop_att.setObjectName("stop_att")
        self.gridLayout.addWidget(self.stop_att, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(LowPassData)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 3, 1, 1)
        self.stop_freq = QtWidgets.QDoubleSpinBox(LowPassData)
        self.stop_freq.setFrame(True)
        self.stop_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_freq.setKeyboardTracking(True)
        self.stop_freq.setDecimals(3)
        self.stop_freq.setObjectName("stop_freq")
        self.gridLayout.addWidget(self.stop_freq, 2, 2, 1, 1)
        self.pass_freq = QtWidgets.QDoubleSpinBox(LowPassData)
        self.pass_freq.setFrame(True)
        self.pass_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_freq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pass_freq.setKeyboardTracking(True)
        self.pass_freq.setDecimals(3)
        self.pass_freq.setObjectName("pass_freq")
        self.gridLayout.addWidget(self.pass_freq, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(LowPassData)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(LowPassData)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.denorm_perc = QtWidgets.QDoubleSpinBox(LowPassData)
        self.denorm_perc.setFrame(True)
        self.denorm_perc.setAlignment(QtCore.Qt.AlignCenter)
        self.denorm_perc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.denorm_perc.setKeyboardTracking(True)
        self.denorm_perc.setDecimals(3)
        self.denorm_perc.setObjectName("denorm_perc")
        self.gridLayout.addWidget(self.denorm_perc, 5, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(LowPassData)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.gain = QtWidgets.QDoubleSpinBox(LowPassData)
        self.gain.setFrame(True)
        self.gain.setAlignment(QtCore.Qt.AlignCenter)
        self.gain.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gain.setKeyboardTracking(True)
        self.gain.setDecimals(3)
        self.gain.setObjectName("gain")
        self.gridLayout.addWidget(self.gain, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(LowPassData)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.q_max = QtWidgets.QDoubleSpinBox(LowPassData)
        self.q_max.setFrame(True)
        self.q_max.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.q_max.setKeyboardTracking(True)
        self.q_max.setDecimals(3)
        self.q_max.setObjectName("q_max")
        self.gridLayout.addWidget(self.q_max, 8, 2, 1, 1)
        self.denorm_select = QtWidgets.QComboBox(LowPassData)
        self.denorm_select.setObjectName("denorm_select")
        self.denorm_select.addItem("")
        self.denorm_select.addItem("")
        self.denorm_select.addItem("")
        self.gridLayout.addWidget(self.denorm_select, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(LowPassData)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(LowPassData)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(LowPassData)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(LowPassData)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(LowPassData)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(LowPassData)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.order_fixed = QtWidgets.QCheckBox(LowPassData)
        self.order_fixed.setObjectName("order_fixed")
        self.gridLayout.addWidget(self.order_fixed, 7, 1, 1, 1)
        self.order = QtWidgets.QDoubleSpinBox(LowPassData)
        self.order.setFrame(True)
        self.order.setAlignment(QtCore.Qt.AlignCenter)
        self.order.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.order.setKeyboardTracking(True)
        self.order.setDecimals(3)
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 7, 2, 1, 1)
        self.q_fixed = QtWidgets.QCheckBox(LowPassData)
        self.q_fixed.setObjectName("q_fixed")
        self.gridLayout.addWidget(self.q_fixed, 8, 1, 1, 1)

        self.retranslateUi(LowPassData)
        QtCore.QMetaObject.connectSlotsByName(LowPassData)

    def retranslateUi(self, LowPassData):
        _translate = QtCore.QCoreApplication.translate
        LowPassData.setWindowTitle(_translate("LowPassData", "Form"))
        self.label_11.setText(_translate("LowPassData", "Denorm.:"))
        self.label_2.setText(_translate("LowPassData", "dB"))
        self.label_4.setText(_translate("LowPassData", "Hz"))
        self.label_10.setText(_translate("LowPassData", "dB"))
        self.label_12.setText(_translate("LowPassData", "%"))
        self.label_8.setText(_translate("LowPassData", "dB"))
        self.label_15.setText(_translate("LowPassData", "Max Q:"))
        self.label_6.setText(_translate("LowPassData", "Hz"))
        self.denorm_select.setItemText(0, _translate("LowPassData", "fp"))
        self.denorm_select.setItemText(1, _translate("LowPassData", "fa"))
        self.denorm_select.setItemText(2, _translate("LowPassData", "Other freq."))
        self.label_9.setText(_translate("LowPassData", "Stopband Att. (Aa):"))
        self.label_7.setText(_translate("LowPassData", "Passband Att. (Ap):"))
        self.label_5.setText(_translate("LowPassData", "Stopband freq. (fa):"))
        self.label_3.setText(_translate("LowPassData", "Passband freq. (fp):"))
        self.label.setText(_translate("LowPassData", "Gain (G):"))
        self.label_13.setText(_translate("LowPassData", "Filter order:"))
        self.order_fixed.setText(_translate("LowPassData", "Fixed:"))
        self.q_fixed.setText(_translate("LowPassData", "Fixed:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LowPassData = QtWidgets.QWidget()
    ui = Ui_LowPassData()
    ui.setupUi(LowPassData)
    LowPassData.show()
    sys.exit(app.exec_())
